# Generated by Django 5.2.6 on 2025-09-30 08:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('click_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, help_text='Optional owner of the short URL', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='unknown', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='unknown', max_length=100)),
                ('language', models.CharField(blank=True, default='unknown', max_length=50)),
                ('os_type', models.CharField(blank=True, default='unknown', max_length=50)),
                ('device', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='url_shortner.url')),
            ],
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_code'], name='url_shortne_short_c_3efd0b_idx'),
        ),
    ]
