# Generated by Django 5.2.6 on 2025-09-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='city',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True),
        ),
    ]
