# Generated by Django 5.2.6 on 2025-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_alter_click_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expiry',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
